import Head from 'next/head';
import Layout from '../../../components/layout';
import Link from 'next/link';
import prisma from '../../../prisma/prisma';
import Navbar from '../../../components/navbar';
import { getSession } from 'next-auth/react';
import GlobalDashboardTable from '../../../components/dashtable_v2';
import React from 'react';
import {
  createSuperblockDashboardObject,
  getTotalChallengesForSuperblocks,
  getDashedNamesURLs,
  getSuperBlockJsons,
  fetchStudentData,
  checkIfStudentHasProgressDataForSuperblocksSelectedByTeacher
} from '../../../util/api_proccesor';
import redirectUser from '../../../util/redirectUser.js';
import { getCurriculumForCertifications } from '../../../util/curriculumService';

export async function getServerSideProps(context) {
  //making sure User is the teacher of this classsroom's dashboard
  const userSession = await getSession(context);
  if (!userSession) {
    return redirectUser('/error');
  }

  const userEmail = await prisma.User.findMany({
    where: {
      email: userSession['user']['email']
    }
  });

  const classroomTeacherId = await prisma.classroom.findUnique({
    where: {
      classroomId: context.params.id
    },
    select: {
      classroomTeacherId: true
    }
  });

  if (
    classroomTeacherId == null ||
    userEmail[0].id == null ||
    userEmail[0].id !== classroomTeacherId['classroomTeacherId']
  ) {
    return redirectUser('/classes');
  }

  const certificationNumbers = await prisma.classroom.findUnique({
    where: {
      classroomId: context.params.id
    },
    select: {
      fccCertifications: true
    }
  });

  let superblockURLS = await getDashedNamesURLs(
    certificationNumbers.fccCertifications
  );

  let superBlockJsons = await getSuperBlockJsons(superblockURLS); // this is an array of urls
  let dashboardObjs = await createSuperblockDashboardObject(superBlockJsons);

  let totalChallenges = getTotalChallengesForSuperblocks(dashboardObjs);

  // Fetch curriculum data from GraphQL for this classroom's certifications
  // Convert certification indices to names for the GraphQL query
  const certificationNames = dashboardObjs
    .map(blocks => (blocks.length > 0 ? blocks[0].superblock : null))
    .filter(Boolean);

  console.log(
    `[Dashboard ${context.params.id}] Fetching curriculum for certifications:`,
    certificationNames
  );
  const curriculumMap = await getCurriculumForCertifications(
    certificationNames
  );
  console.log(
    `[Dashboard ${context.params.id}] Curriculum map contains ${
      Object.keys(curriculumMap).length
    } challenges`
  );

  let studentData = await fetchStudentData(
    context.params.id,
    context,
    curriculumMap
  );

  // Temporary check to map/accomodate hard-coded mock student data progress in unselected superblocks by teacher
  let studentsAreEnrolledInSuperblocks =
    checkIfStudentHasProgressDataForSuperblocksSelectedByTeacher(
      studentData,
      dashboardObjs
    );
  studentData.forEach(studentJSON => {
    let indexToCheckProgress = studentData.indexOf(studentJSON);
    let isStudentEnrolledInAtLeastOneSuperblock =
      studentsAreEnrolledInSuperblocks[indexToCheckProgress].every(
        val => val === true
      );

    if (!isStudentEnrolledInAtLeastOneSuperblock) {
      studentData[indexToCheckProgress].certifications = [];
    }
  });

  return {
    props: {
      userSession,
      classroomId: context.params.id,
      studentData,
      totalChallenges: totalChallenges,
      studentsAreEnrolledInSuperblocks
    }
  };
}

export default function Home({
  userSession,
  classroomId,
  totalChallenges,
  studentData,
  studentsAreEnrolledInSuperblocks
}) {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {userSession && (
        <>
          <Navbar>
            <div className='border-solid border-2 pl-4 pr-4'>
              <Link href={'/classes'}>Classes</Link>
            </div>
            <div className='border-solid border-2 pl-4 pr-4'>
              <Link href={'/'}> Menu</Link>
            </div>
          </Navbar>
          <GlobalDashboardTable
            classroomId={classroomId}
            totalChallenges={totalChallenges}
            studentData={studentData}
            studentsAreEnrolledInSuperblocks={studentsAreEnrolledInSuperblocks}
          ></GlobalDashboardTable>
        </>
      )}
    </Layout>
  );
}
